version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    groups:
      maven-production:
        dependency-type: production
      maven-development:
        dependency-type: development
