package io.atlasarc.archunit.internal

import com.tngtech.archunit.core.domain.JavaClass

/**
 * Conservative filter for Kotlin compiler-generated bytecode noise.
 *
 * Default policy:
 * - Ignore [kotlin.Metadata] as a dependency target (every Kotlin class carries it).
 * - Ignore all `kotlin.*` stdlib dependencies (non-project, never architectural).
 * - Do NOT ignore `*Kt` top-level function classes — they may be real package dependencies.
 * - Do NOT ignore `$Companion` classes — companion objects can be escape hatches.
 * - Do NOT ignore `$DefaultImpls` — until acquisition fixtures (step 11) prove they are noise.
 *
 * Extend this policy only when acquisition fixtures demonstrate a specific pattern
 * is consistently noise rather than architecture.
 */
internal class KotlinBytecodeFilter {

    /**
     * Returns true if the class should be entirely excluded from extraction
     * (neither its outgoing accesses nor structural dependencies will be emitted).
     */
    fun ignoreClass(clazz: JavaClass): Boolean {
        // kotlin.Metadata is not a project class. If it appears as a class to walk,
        // ignore it — but it should not appear if importPaths() was called with
        // project-only roots. Guard here anyway.
        if (clazz.name == "kotlin.Metadata") return true
        return false
    }

    /**
     * Returns true if a [RichDependencyRecord] should be excluded after construction.
     *
     * Applied after the record is built so that filtering decisions can inspect
     * both origin and target.
     */
    fun ignoreDependency(record: RichDependencyRecord): Boolean {
        // kotlin.Metadata dependency — every Kotlin class carries @Metadata.
        if (record.targetClass == "kotlin.Metadata") return true
        // Kotlin stdlib — never project-internal.
        if (record.targetPackage.startsWith("kotlin.")) return true
        if (record.targetPackage.startsWith("kotlinx.")) return true
        return false
    }
}
